Replace mentions in message content with corresponding usernames
AmaranthineCodices/chrysanthemum pull request #38
Opened 2024-02-10 16:22 UTC by Archasion

2024-02-11 04:17 UTC, Phalanxia approved these changes
This looks good to me but I am not very familiar with Rust. Let's have @AmaranthineCodices  review it too before merging!

2024-02-11 22:06 UTC, AmaranthineCodices requested changes
one concern about copying the content string. otherwise minor comments but looks good

2024-02-11 22:06 UTC, AmaranthineCodices commented on src/main.rs
> +                update.mentions.as_ref().unwrap_or(&vec![]),
this avoids creating a temporary `Vec` (I think it gets optimized away regardless but still)
```suggestion
                update.mentions.as_deref().unwrap_or(&[]),
```

2024-02-11 22:06 UTC, AmaranthineCodices commented on src/message.rs
> +    use super::MentionTrait;
prefer importing this from `twilight` itself; this makes it appear like `MentionTrait` is coming from Chrysanthemum itself
```suggestion
    use twilight_mention::Mention as MentionTrait;
```

2024-02-11 22:06 UTC, AmaranthineCodices commented on src/message.rs
> +pub(crate) fn clean_mentions(content: &str, mentions: &[Mention]) -> String {
This has the effect of _always_ copying the content string, which is up to 4096 bytes (or more, depending on the exact details of Discord's character limit). That could be kind of expensive if the message is very long but doesn't include any mentions.

I'd like to either:
- avoid invoking this method if we have no mentions, OR
- return a `Cow<str>` or something in the case of there being no mentions at all

2024-05-04 22:23 UTC, AmaranthineCodices approved these changes

2024-05-04 22:24 UTC, merged